import { NextRequest } from "next/server";
import { runPipelineWithGitHub } from "@/lib/agents/pipeline-github";
import { chatCompletion } from "@/lib/deepseek";
import { execute, queryOne, query } from "@/lib/db";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function sseEvent(event: string, data: unknown): string {
  return `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
}

async function autoGenerateDailyReport(productId: number, pipelineSummary: string, messages: { role: string; content: string }[]): Promise<void> {
  try {
    const product = await queryOne<{ name: string }>("SELECT name FROM products WHERE id = ?", [productId]);
    const productName = product?.name || `产品#${productId}`;

    const roleOutputs = messages
      .filter(m => !m.content.startsWith("[失败]"))
      .map(m => `[${m.role}] ${m.content.substring(0, 300)}`)
      .join("\n");

    const dailyContent = await chatCompletion(
      "你是项目经理，根据团队今日分析结果生成简洁日报。严格按以下格式：\n\n## ✅ 今日进展\n（3-5条要点）\n\n## ⚠️ 存在问题\n（1-3条问题）\n\n## 📌 下一步计划\n（3-5条行动计划）",
      `产品：${productName}\n\n团队分析结果：\n${roleOutputs}\n\n执行摘要：${pipelineSummary}`,
      { temperature: 0.4, maxTokens: 1500 }
    );

    await execute(
      "INSERT INTO daily_reports (product_id, content) VALUES (?, ?)",
      [productId, dailyContent]
    );
  } catch (err) {
    console.error("自动生成日报失败:", err);
  }
}

export async function POST(request: NextRequest) {
  const body = await request.json();
  const { productId, inputPrompt, withGitHub } = body;

  if (!productId) {
    return new Response(sseEvent("error", { message: "productId 不能为空" }), {
      status: 400,
      headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache", Connection: "keep-alive" },
    });
  }

  const prompt = inputPrompt || "请对这个产品进行全面团队分析评估。";
  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const send = (e: string, d: unknown) => controller.enqueue(encoder.encode(sseEvent(e, d)));

      try {
        if (withGitHub) {
          const result = await runPipelineWithGitHub(Number(productId), prompt, (evt) => send(evt.type, evt));
          await autoGenerateDailyReport(Number(productId), result.run.summary || "", result.messages);
          send("done", {
            run: result.run,
            messageCount: result.messages.length,
            github: result.github,
          });
        } else {
          const { runPipelineWithProgress } = await import("@/lib/agents/pipeline");
          const result = await runPipelineWithProgress(Number(productId), prompt, "manual", (evt) => send(evt.type, evt));
          await autoGenerateDailyReport(Number(productId), result.run.summary || "", result.messages);
          send("done", {
            run: result.run,
            messageCount: result.messages.length,
          });
        }
      } catch (err) {
        send("error", { message: err instanceof Error ? err.message : "执行失败" });
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache", Connection: "keep-alive" },
  });
}
